version: "2"
run:
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  enable:
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - misspell
    - revive
    - unconvert
  # gosec disabled — Trivy covers security scanning in CI
  settings:
    dupl:
      threshold: 200
    errcheck:
      check-type-assertions: true
      check-blank: true
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - commentFormatting
        - hugeParam
        - ifElseChain
      enabled-tags:
        - diagnostic
        - style
        - performance
    gocyclo:
      min-complexity: 25
    govet:
      enable-all: true
      disable:
        - fieldalignment
    lll:
      line-length: 140
    misspell:
      locale: US
    revive:
      rules:
        - name: package-comments
          disabled: true
        - name: var-naming
          disabled: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
        path: _test\.go
      - linters:
          - staticcheck
        text: 'SA9003:'
      - linters:
          - goconst
          - gocyclo
        path: internal/cli/
      - linters:
          - revive
        text: 'unused-parameter'
      - linters:
          - revive
        text: 'exported:'
      - linters:
          - misspell
        text: 'Spectre'
      - linters:
          - errcheck
        source: '// Best-effort'
      - linters:
          - errcheck
        path: internal/filter/
      - linters:
          - goconst
          - dupl
        path: internal/detector/
    paths:
      - vendor
      - bin
      - .github
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/ppiankov/infranow
  exclusions:
    generated: lax
    paths:
      - vendor
      - bin
      - .github
      - third_party$
      - builtin$
      - examples$
